// Generated by scripts/export-abi.mjs from Foundry artifacts. Do not edit.
export { issuerRegistryAbi } from "./IssuerRegistry";
export { credentialRegistryAbi } from "./CredentialRegistry";
export { credentialSBTAbi } from "./CredentialSBT";
