// Generates abi/*.ts (`export const xxxAbi = [...] as const`) from Foundry artifacts in out/.
// The generated files are committed so apps can build without Foundry (e.g. on Vercel).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const contracts = ["IssuerRegistry", "CredentialRegistry", "CredentialSBT"];
const header = "// Generated by scripts/export-abi.mjs from Foundry artifacts. Do not edit.\n";

for (const name of contracts) {
  const artifact = JSON.parse(readFileSync(join(root, "out", `${name}.sol`, `${name}.json`), "utf8"));
  const exportName = `${name[0].toLowerCase()}${name.slice(1)}Abi`;
  const body = `${header}export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(join(root, "abi", `${name}.ts`), body);
}

const index = contracts
  .map((name) => `export { ${name[0].toLowerCase()}${name.slice(1)}Abi } from "./${name}";`)
  .join("\n");
writeFileSync(join(root, "abi", "index.ts"), `${header}${index}\n`);
console.log(`Exported ${contracts.length} ABIs to abi/`);
